# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=4000)),
                ('lokalizacja', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=250)),
                ('kategoria', models.CharField(max_length=250)),
                ('tytul', models.CharField(max_length=250)),
                ('zdjecie', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.Items'),
        ),
    ]
