# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Items',
        ),
        migrations.AddField(
            model_name='items',
            name='lokalizacja',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='opis',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
