# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0002_auto_20170525_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=4000)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='opis',
        ),
        migrations.AddField(
            model_name='item',
            name='Items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.Items'),
        ),
    ]
